from tkMessageBox import*
from tkFileDialog import*
from Tkinter import*
import sqlite3
root7=Tk()
root7.configure(background="Blue")
root7.title("Python Project")
Label(root7,text="Bank Registration Portal",font="times 20 bold italic").grid(row=0,column=0,columnspan=2)
Label(root7,text="Name-Rashmi Agnihotri").grid(row=1,column=0)
Label(root7,text="Enrollement Number-161B167").grid(row=2,column=0)
Label(root7,text="Batch-B6").grid(row=3,column=0)
Label(root7,text="Submitted to-Sir Mahesh Kumar").grid(row=4,column=0)
root7.after(7000,root7.destroy)
root7.mainloop()
root=Tk()
a=PhotoImage(file='cash2.gif')
Label(root,image=a).grid(row=0,column=0,columnspan=4)
Label(root,text="Bank Of India",relief='ridge',font='times 30 bold italic',bg='blue').grid(row=1,column=1,columnspan=2)
Label(root,text="Welcomes You",font='times 20 bold italic').grid(row=2,column=1,columnspan=2)
Label(root,text="Online Account Opening",font='times 10 bold italic').grid(row=4,column=2) 
Label(root,text="At present Home lone=@8.60%",font='times 10 bold italic').grid(row=4,column=0)
Label(root,text="At present Car Loan=@8.70%",font='times 10 bold italic').grid(row=4,column=1)
Label(root,text="Bank Loan Scheme",font='times 10 bold italic').grid(row=4,column=3)
def fun():
    root5=Tk()
    root5.title(" Write Your Query or complain")
    root5.minsize(width=400,height=440)
    root5.maxsize(width=400,height=440)
    text=Text(root5)
    text.grid(row=0,column=1)
    def show():
        conn = sqlite3.connect('show1.db')
        curs = conn.cursor()
        curs.execute("create table if not exists complain3 (text varchar(50000))")
        values = [text.get("1.0", "end-1c")]
        curs.executemany('insert into complain3 values(?)',[values])
        curs.execute("select * from complain3")
        print curs.fetchall()
        conn.commit()
        conn.close()
        showinfo("Confirmation","We will contact you soon")
        root5.destroy()
    Button(root5,text="Submit",font="times 20 bold italic",bg="light blue",command=show).grid(row=1,column=1)
    root5.mainloop()
def carLoan():
    root4=Tk()
    root4.title("Get Instant Approval")
    Label(root4,text=" If you already have account then Account Number").grid(row=0,column=0)
    v7=Entry(root4)
    v7.grid(row=1,column=0)
    Label(root4,text="Enter your mobile number with ISD Code").grid(row=2,column=0)
    v8=Entry(root4)
    v8.grid(row=3,column=0)
    def database1():
        conn = sqlite3.connect('carloan1.db')
        curs = conn.cursor()
        curs.execute("create table if not exists carloan2 (account_number number(25), mobile_number number(12))")
        values = [(v7.get(),v8.get())]
        curs.executemany('insert into carloan2 values(?,?)', values,)
        curs.execute("select * from carloan2")
        print curs.fetchall()
        conn.commit()
        conn.close()
        showinfo("Confirmation","We will contact you soon")
        root4.destroy()
    Button(root4,text="Submit",font='times 10 bold italic',command=database1).grid(row=4,column=0)
    root4.mainloop()
Button(root,text="Apply now for Car Loan",font='times 15 bold italic',bg='light blue',command=carLoan).grid(row=3,column=1)
def HomeLoan():
    root1=Tk()
    root1.title("Get Instant Approval")
    Label(root1,text=" If you already have account then Account Number").grid(row=0,column=0)
    v7=Entry(root1)
    v7.grid(row=1,column=0)
    Label(root1,text="Enter your mobile number with ISD Code").grid(row=2,column=0)
    v8=Entry(root1)
    v8.grid(row=3,column=0)
    def database2():
        conn = sqlite3.connect('Homeloan1.db')
        curs = conn.cursor()
        curs.execute("create table if not exists Homeloan2 (account_number number(25), mobile_number number(12))")
        values = [(v7.get(),v8.get())]
        curs.executemany('insert into Homeloan2 values(?,?)', values,)
        curs.execute("select * from Homeloan2")
        print curs.fetchall()
        conn.commit()
        conn.close()
        showinfo("Confirmation","We will contact you soon")
        root1.destroy()
    Button(root1,text="Submit",font='times 10 bold italic',command=database2).grid(row=4,column=0)
    root1.mainloop()
    root1.destroy()
Button(root,text="Apply now for Home Loan",font='times 15 bold italic',bg='light blue',command=HomeLoan).grid(row=3,column=0)
def PersonalLoan():
    root2=Tk()
    root2.title("Get Instant Approval")
    Label(root2,text=" If you already have account then Account Number").grid(row=0,column=0)
    v7=Entry(root2)
    v7.grid(row=1,column=0)
    Label(root2,text="Enter your mobile number with ISD Code").grid(row=2,column=0)
    v8=Entry(root2)
    v8.grid(row=3,column=0)
    def database3():
        conn = sqlite3.connect('Personalloan1.db')
        curs = conn.cursor()
        curs.execute("create table if not exists Personalloan2 (account_number number(25), mobile_number number(12))")
        values = [(v7.get(),v8.get())]
        curs.executemany('insert into Personalloan2 values(?,?)', values,)
        curs.execute("select * from Personalloan2")
        print curs.fetchall()
        conn.commit()
        conn.close()
        showinfo("Confirmation","We will contact you soon")
        root2.destroy()
    Button(root2,text="Submit",font='times 10 bold italic',command=database3).grid(row=4,column=0)
    root2.mainloop()
Button(root,text="Apply now for Personal Loan",font='times 15 bold italic',bg='light blue',command=PersonalLoan).grid(row=3,column=3)
def AccountOpening():
    root3=Tk()
    root3.title("Get Instant Approval")
    Label(root3,text="Personal Details",font='times 20 bold italic',bg='blue').grid(row=0,column=0)
    Label(root3,text="Name").grid(row=1,column=0)
    e1=Entry(root3)
    e1.grid(row=1,column=1)
    Label(root3,text="Nationality").grid(row=2,column=0)
    e2=Entry(root3)
    e2.grid(row=2,column=1)
    Label(root3,text="Mother's Name").grid(row=3,column=0)
    e3=Entry(root3)
    e3.grid(row=3,column=1)
    Label(root3,text="Name of father").grid(row=4,column=0)
    e4=Entry(root3)
    e4.grid(row=4,column=1)
    Label(root3,text="Name of spouse(if any)").grid(row=5,column=0)
    e5=Entry(root3)
    e5.grid(row=5,column=1)
    Label(root3,text="Adress",font="times 20 bold italic",bg='blue').grid(row=6,column=0)
    Label(root3,text="Door/Flat No;Building/Society").grid(row=7,column=0)
    e6=Entry(root3)
    e6.grid(row=7,column=1)
    Label(root3,text="Street/Road Name/Block").grid(row=8,column=0)
    e7=Entry(root3)
    e7.grid(row=8,column=1)
    Label(root3,text="District").grid(row=9,column=0)
    e8=Entry(root3)
    e8.grid(row=9,column=1)
    Label(root3,text="City").grid(row=10,column=0)
    e9=Entry(root3)
    e9.grid(row=10,column=1)
    Label(root3,text="State").grid(row=11,column=0)
    e10=Entry(root3)
    e10.grid(row=11,column=1)
    Label(root3,text="Pin").grid(row=12,column=0)
    e11=Entry(root3)
    e11.grid(row=12,column=1)
    Label(root3,text="Country").grid(row=13,column=0)
    e12=Entry(root3)
    e12.grid(row=13,column=1)
    Label(root3,text="Account Information",font='times 20 bold italic',bg='blue').grid(row=14,column=0)
    Label(root3,text="Branch code").grid(row=15,column=0)
    e13=Entry(root3)
    e13.grid(row=15,column=1)
    Label(root3,text="Branch Name").grid(row=16,column=0)
    e14=Entry(root3)
    e14.grid(row=16,column=1)
    Label(root3,text="Mobile Number(For SMS Alert)").grid(row=17,column=0)
    e15=Entry(root3)
    e15.grid(row=17,column=1)
    Label(root3,text="Threshold Amount").grid(row=18,column=0)
    e16=Entry(root3)
    e16.grid(row=18,column=1)
    def database4():
        conn = sqlite3.connect('AccountOpening.db')
        curs = conn.cursor()
        curs.execute("create table if not exists AccountOpening2 (name varchar(15),nationality varchar(15),Mother_name varchar(20),Father_name varchar(20),spouse_name varchar(20),door varchar(50),Street varchar(50),District varchar(20),City varchar(20),state varchar(20),pin number(25),country varchar(25),Branch_code varchar(25),Branch_name varchar(25),Mobile_number number(12),threshold_amount number(10))")
        values = [(e1.get(),e2.get(),e3.get(),e4.get(),e5.get(),e6.get(),e7.get(),e8.get(),e9.get(),e10.get(),e11.get(),e12.get(),e13.get(),e14.get(),e15.get(),e16.get())]
        curs.executemany('insert into AccountOpening2 values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)', values,)
        curs.execute("select * from AccountOpening2")
        print curs.fetchall()
        conn.commit()
        conn.close()
        showinfo("Confirmation","We will contact you soon")
        root3.destroy()
    Button(root3,text="Submit",font='times 10 bold italic',command=database4).grid(row=19,column=0)
    root3.mainloop()
Button(root,text="Apply now for Saving Bank",font='times 15 bold italic',bg='light blue',command=AccountOpening).grid(row=3,column=2)   
Button(root,text="May I help You ?",font='times 15 bold italic',bg='light blue',command=fun).grid(row=5,column=3)
root.mainloop()
        
        

      
